# Generated by Django 4.1 on 2022-08-15 08:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import taggit.managers
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('time_zone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/Moscow', verbose_name='часовой пояс')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='дата и время запуска рассылки')),
                ('text', models.TextField(max_length=500, verbose_name='текст сообщения')),
                ('end_dt', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='OperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='код мобильного оператора')),
            ],
            options={
                'verbose_name': 'код оператора',
                'verbose_name_plural': 'коды операторов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='клиент')),
                ('mailing_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailinglist', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mailing.operatorcode', verbose_name='код мобильного оператора'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='client',
            name='operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mailing.operatorcode', verbose_name='код мобильного оператора'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
